# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - amrutha  
  paths:
    exclude:
      - README.md  

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    displayName: 'Build stage'
    jobs:
      - job: Build
        displayName: 'Build job'
        steps:
          - script: echo 'Building the project...'
            displayName: 'Build project'

  - stage: Test
    displayName: 'Test stage'
    jobs:
      - job: Test
        displayName: 'Test job'
        steps:
          - script: echo 'Running tests...'
            displayName: 'Run tests'

  - stage: Deploy
    displayName: 'Deploy stage'
    jobs:
      - job: Deploy
        displayName: 'Deploy job'
        condition: succeeded()
        steps:
          - script: echo 'Deploying to production...'
            displayName: 'Deploy to production'
